export const OPTIONS = {
asthmaTypeOptions: [
  "allergisch astma",
  "ernstig astma",
  "inspanningsastma",
  "niet-allergisch astma" ],
  triggerOptions: [
    { id: 0,
      key:'Mist',
      checked:false,
    },
    { id: 1,
      key: 'Koude lucht',
      checked:false,
    },
    { id: 2,
      key:'Warme lucht',
      checked:false,
    },
    { id: 3,
      key: 'Huisstofmijt',
      checked:false,
    },
    { id: 4,
      key:'Rook',
      checked:false,
    },
    { id: 5,
      key: 'Huidschilfers',
      checked:false,
    },
    { id: 6,
      key: 'Parfum',
      checked:false,
    },
    { id: 7,
      key: 'Stuifmeel',
      checked:false,
    },
    { id: 8,
      key: 'Pollen',
      checked:false,
    }
  ],
  medicationOptions: [
    { id: 0,
      key:'Budesonide',
      checked:false,
    },
    { id: 1,
      key: 'Salbutamol',
      checked:false,
    },
  ]
}
